import { StyleSheet, Dimensions } from "react-native";

const windowWidth = Dimensions.get("window").width;

export default StyleSheet.create({
	container: {
		flex: 1,
		alignItems: "center",
		backgroundColor: "#F5F9FF",
	},
	title: {},
	logo: {
		flex: 1,
		height: 200,
		width: 200,
		alignSelf: "center",
		borderRadius: 10,
		margin: 30,
	},
	text: {
		marginTop: 7,
		marginLeft: 30,
		marginRight: 30,
		paddingLeft: 16,
		alignItems: "center",
		justifyContent: "center",
		alignSelf: "center",
	},
	input: {
		height: 48,
		borderRadius: 7,
		overflow: "hidden",
		backgroundColor: "#ffffff",
		shadowColor: "#000000",
		shadowOffset: { width: 0, height: 5 },
		shadowOpacity: 0.3,
		shadowRadius: 5,
		elevation: 5,
		marginVertical: 10,
		marginHorizontal: 30,
		paddingLeft: 16,
	},
	button: {
		backgroundColor: "#0B3802",
		shadowColor: "#000000",
		shadowOffset: { width: 0, height: 5 },
		shadowOpacity: 0.3,
		shadowRadius: 5,
		elevation: 5,
		marginHorizontal: 30,
		marginVertical: 20,
		height: 48,
		borderRadius: 7,
		alignItems: "center",
		justifyContent: "center",
	},
	buttonTitle: {
		color: "white",
		fontSize: 16,
		fontWeight: "bold",
		
	},
	modalContainer: {
		flex: 1,
		backgroundColor: "#F5F9FF",
		justifyContent: "center",
		alignItems: "center",
		paddingHorizontal: 60,
	},
	modalContent: {
		backgroundColor: "#fff",
		padding: 20,
		borderRadius: 10,
		alignItems: "center",
	},
	modalButton: {
		backgroundColor: "#fff",
		shadowColor: "#000000",
		shadowOffset: { width: 0, height: 5 },
		shadowOpacity: 0.3,
		shadowRadius: 5,
		elevation: 5,
		marginHorizontal: 30,
		marginVertical: 20,
		height: 64,
		width: windowWidth - 210,
		borderRadius: 7,
		alignItems: "center",
		justifyContent: "center",
	},
	modalButtonText: {
		color: "black",
		fontSize: 16,
		fontWeight: "bold",
	},
});
